import { Alert } from "bootstrap";
import React, { Component } from "react";

const Context = React.createContext();

export class Provider extends Component {
  newobject = (action, newComments) => {
    switch (action) {
      case "add_comments":
        this.setState({
          comments: [newComments, ...this.state.comments],
        });
        console.log("hooo", this.state.comments);

      case "add_Loginss":
        this.setState({
          signin: [newComments, ...this.state.signin],
        });
        console.log("hooo", this.state.signin);

      case "add_cart":
        this.setState({
          cart: [newComments, ...this.state.cart],
        });
        console.log("hooo", this.state.cart);
    }

    console.log("action", action);
  };
  state = {
    newobject: this.newobject,
    itemsarr: [
      {
        id: 0,
        name: "carrot",
        imgs: "carrot",
        Rs: 40,
      },
      {
        id: 1,
        name: "apple",
        imgs: "apple",
        Rs: 30,
      },
      {
        id: 2,
        name: "banana",
        imgs: "banana",
        Rs: 10,
      },
      {
        id: 3,
        name: "bell_pepper",
        imgs: "bell_pepper",
        Rs: 20,
      },
      {
        id: 4,
        name: "chili",
        imgs: "chili",
        Rs: 5,
      },
      {
        id: 5,
        name: "orange",
        imgs: "orange",
        Rs: 25,
      },
      {
        id: 6,
        name: "mango",
        imgs: "mango",
        Rs: 20,
      },
      {
        id: 7,
        name: "potato",
        imgs: "potato",
        Rs: 21,
      },
      {
        id: 8,
        name: "pumpkin",
        imgs: "pumpkin",
        Rs: 23,
      },
      {
        id: 9,
        name: "strawberry",
        imgs: "strawberry",
        Rs: 40,
      },
      {
        id: 10,
        name: "watermelon",
        imgs: "watermelon",
        Rs: 30,
      },
    ],
    cart: [],
    comments: [
      {
        id: 1,
        name: "asdv",
        comments: "suppper",
      },
    ],
    signin: [
      {
        name: "gunalan",
        birthday: 11 - 3 - 2002,
        phone: 943424432,
        email: "gunalandeedzooy@gmail.com",
        pass: "asgverver",
        address: "lig 249 gandhi manager covi",
      },
    ],
    aaa: [
      {
        id: 0,
        name: "carrot",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "carrot",
        review: 3,
        items: "covi",
        kg: 4,
      },
      {
        id: 1,
        name: "apple",
        com: "it is very good for our body...",
        Rs: 40,
        imgs: "apple",
        review: 4,
        items: "palani",
        kg: 3,
      },
      {
        id: 2,
        name: "mango",
        com: "it is very good for our body...",
        Rs: 50,
        imgs: "mango",
        review: 5,
        items: "palani",
        kg: 9,
      },
      {
        id: 3,
        name: "banana",
        com: "it is very good for our body...",
        Rs: 10,
        imgs: "banana",
        review: 4,
        items: "palani",
        kg: 5,
      },
      {
        id: 4,
        name: "bell_pepper",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "bell_pepper",
        review: 3,
        items: "palani",
        kg: 5,
      },
      {
        id: 5,
        name: "chili",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "chili",
        review: 5,
        items: "palani",
        kg: 4,
      },
      {
        id: 6,
        name: "orange",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "orange",
        review: 3,
        items: "palani",
        kg: 10,
      },
      {
        id: 7,
        name: "potato",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "potato",
        review: 5,
        items: "palani",
        kg: 20,
      },
      {
        id: 8,
        name: "pumpkin",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "pumpkin",
        review: 4,
        items: "palani",
        kg: 4,
      },
      {
        id: 9,
        name: "strawberry",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "strawberry",
        review: 3,
        items: "palani",
        kg: 10,
      },
      {
        id: 10,
        name: "watermelon",
        com: "it is very good for our body...",
        Rs: 40,
        imgs: "watermelon",
        review: 4,
        items: "palani",
        kg: 10,
      },
      {
        id: 11,
        name: "carrot",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "carrot",
        review: 3,
        items: "palani",
        kg: 10,
      },
      {
        id: 12,
        name: "apple",
        com: "it is very good for our body...",
        Rs: 40,
        imgs: "apple",
        review: 4,
        items: "palani",
        kg: 10,
      },
      {
        id: 13,
        name: "mango",
        com: "it is very good for our body...",
        Rs: 50,
        imgs: "mango",
        review: 5,
        items: "palani",
        kg: 10,
      },
      {
        id: 14,
        name: "banana",
        com: "it is very good for our body...",
        Rs: 10,
        imgs: "banana",
        review: 4,
        items: "palani",
        kg: 10,
      },
      {
        id: 15,
        name: "bell_pepper",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "bell_pepper",
        review: 3,
        items: "palani",
        kg: 10,
      },
      {
        id: 16,
        name: "chili",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "chili",
        review: 5,
        items: "palani",
        kg: 10,
      },
      {
        id: 17,
        name: "orange",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "orange",
        review: 3,
        items: "palani",
        kg: 10,
      },
      {
        id: 18,
        name: "potato",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "potato",
        review: 5,
        items: "palani",
        kg: 10,
      },
      {
        id: 19,
        name: "pumpkin",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "pumpkin",
        review: 4,
        items: "palani",
        kg: 10,
      },
      {
        id: 20,
        name: "strawberry",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "strawberry",
        review: 3,
        items: "palani",
        kg: 10,
      },
      {
        id: 21,
        name: "watermelon",
        com: "it is very good for our body...",
        Rs: 40,
        imgs: "watermelon",
        review: 4,
        items: "palani",
        kg: 10,
      },
      {
        id: 22,
        name: "carrot",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "carrot",
        review: 3,
        items: "palani",
        kg: 10,
      },
      {
        id: 23,
        name: "apple",
        com: "it is very good for our body...",
        Rs: 40,
        imgs: "apple",
        review: 4,
        items: "palani",
        kg: 10,
      },

      {
        id: 24,
        name: "mango",
        com: "it is very good for our body...",
        Rs: 50,
        imgs: "mango",
        review: 5,
        items: "palani",
        kg: 10,
      },
      {
        id: 25,
        name: "banana",
        com: "it is very good for our body...",
        Rs: 10,
        imgs: "banana",
        review: 4,
        items: "palani",
        kg: 10,
      },
      {
        id: 25,
        name: "bell_pepper",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "bell_pepper",
        review: 3,
        items: "palani",
        kg: 10,
      },
      {
        id: 26,
        name: "chili",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "chili",
        review: 5,
        items: "palani",
        kg: 10,
      },
      {
        id: 27,
        name: "orange",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "orange",
        review: 3,
        items: "palani",
        kg: 10,
      },
      {
        id: 28,
        name: "potato",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "potato",
        review: 5,
        items: "palani",
        kg: 10,
      },
      {
        id: 29,
        name: "pumpkin",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "pumpkin",
        review: 4,
        items: "palani",
        kg: 10,
      },
      {
        id: 30,
        name: "strawberry",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "strawberry",
        review: 3,
        items: "palani",
        kg: 10,
      },
      {
        id: 31,
        name: "watermelon",
        com: "it is very good for our body...",
        Rs: 40,
        imgs: "watermelon",
        review: 4,
        items: "palani",
        kg: 10,
      },
      {
        id: 32,
        name: "carrot",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "carrot",
        review: 3,
        items: "palani",
        kg: 10,
      },
      {
        id: 33,
        name: "apple",
        com: "it is very good for our body...",
        Rs: 40,
        imgs: "apple",
        review: 4,
        items: "palani",
        kg: 10,
      },
      {
        id: 34,
        name: "mango",
        com: "it is very good for our body...",
        Rs: 50,
        imgs: "mango",
        review: 5,
        items: "palani",
        kg: 10,
      },
      {
        id: 35,
        name: "banana",
        com: "it is very good for our body...",
        Rs: 10,
        imgs: "banana",
        review: 4,
        items: "palani",
        kg: 10,
      },
      {
        id: 36,
        name: "bell_pepper",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "bell_pepper",
        review: 3,
        items: "palani",
        kg: 10,
      },
      {
        id: 37,
        name: "chili",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "chili",
        review: 5,
        items: "palani",
        kg: 10,
      },
      {
        id: 38,
        name: "orange",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "orange",
        review: 3,
        items: "palani",
        kg: 10,
      },
      {
        id: 39,
        name: "potato",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "potato",
        review: 5,
        items: "palani",
        kg: 10,
      },
      {
        id: 40,
        name: "pumpkin",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "pumpkin",
        review: 4,
        items: "palani",
        kg: 10,
      },
      {
        id: 41,
        name: "strawberry",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "strawberry",
        review: 3,
        items: "palani",
        kg: 10,
      },
      {
        id: 42,
        name: "watermelon",
        com: "it is very good for our body...",
        Rs: 40,
        imgs: "watermelon",
        review: 4,
        items: "palani",
        kg: 10,
      },
      {
        id: 43,
        name: "carrot",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "carrot",
        review: 3,
        items: "palani",
        kg: 10,
      },
      {
        id: 44,
        name: "apple",
        com: "it is very good for our body...",
        Rs: 40,
        imgs: "apple",
        review: 4,
        items: "palani",
        kg: 10,
      },
      {
        id: 45,
        name: "mango",
        com: "it is very good for our body...",
        Rs: 50,
        imgs: "mango",
        review: 5,
        items: "palani",
        kg: 10,
      },
      {
        id: 46,
        name: "banana",
        com: "it is very good for our body...",
        Rs: 10,
        imgs: "banana",
        review: 4,
        items: "palani",
        kg: 10,
      },
      {
        id: 47,
        name: "bell_pepper",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "bell_pepper",
        review: 3,
        items: "palani",
        kg: 10,
      },
      {
        id: 48,
        name: "chili",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "chili",
        review: 5,
        items: "palani",
        kg: 10,
      },
      {
        id: 49,
        name: "orange",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "orange",
        review: 3,
        items: "palani",
        kg: 10,
      },
      {
        id: 50,
        name: "potato",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "potato",
        review: 5,
      },
      {
        id: 51,
        name: "pumpkin",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "pumpkin",
        review: 4,
        items: "palani",
        kg: 10,
      },
      {
        id: 52,
        name: "strawberry",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "strawberry",
        review: 3,
        items: "palani",
        kg: 10,
      },
      {
        id: 53,
        name: "watermelon",
        com: "it is very good for our body...",
        Rs: 40,
        imgs: "watermelon",
        review: 4,
        items: "palani",
        kg: 10,
      },
      {
        id: 54,
        name: "carrot",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "carrot",
        review: 3,
        items: "palani",
        kg: 10,
      },
      {
        id: 55,
        name: "apple",
        com: "it is very good for our body...",
        Rs: 40,
        imgs: "apple",
        review: 4,
        items: "palani",
        kg: 10,
      },
      {
        id: 56,
        name: "mango",
        com: "it is very good for our body...",
        Rs: 50,
        imgs: "mango",
        review: 5,
        items: "palani",
        kg: 10,
      },
      {
        id: 57,
        name: "banana",
        com: "it is very good for our body...",
        Rs: 10,
        imgs: "banana",
        review: 4,
        items: "palani",
        kg: 10,
      },
      {
        id: 58,
        name: "bell_pepper",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "bell_pepper",
        review: 3,
        items: "palani",
        kg: 10,
      },
      {
        id: 59,
        name: "chili",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "chili",
        review: 5,
        items: "palani",
        kg: 10,
      },
      {
        id: 60,
        name: "orange",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "orange",
        review: 3,
        items: "palani",
        kg: 10,
      },
      {
        id: 61,
        name: "potato",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "potato",
        review: 5,
        items: "palani",
        kg: 10,
      },
      {
        id: 62,
        name: "pumpkin",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "pumpkin",
        review: 4,
        items: "palani",
        kg: 10,
      },
      {
        id: 63,
        name: "strawberry",
        com: "it is very good for our body...",
        Rs: 30,
        imgs: "strawberry",
        review: 3,
        items: "palani",
        kg: 10,
      },
      {
        id: 64,
        name: "watermelon",
        com: "it is very good for our body...",
        Rs: 40,
        imgs: "watermelon",
        review: 4,
        items: "palani",
        kg: 10,
      },
    ],
    aa: [
      {
        id: "q234ewq",
        from: "covi",
        to: "palani",
        kg: 2,
      },
      {
        id: 1,
        from: "palani",
        to: "covi",
        kg: 2,
      },
      {
        id: 2,
        from: "covi",
        to: "palani",
        kg: 2,
      },
      {
        id: 3,
        from: "covi",
        to: "palani",
        kg: 2,
      },
      {
        id: 4,
        from: "covi",
        to: "palani",
        kg: 2,
      },
      {
        id: 5,
        from: "covi",
        to: "palani",
        kg: 2,
      },
      {
        id: 6,
        from: "covi",
        to: "palani",
        kg: 2,
      },
      {
        id: 7,
        from: "covi",
        to: "palani",
        kg: 2,
      },
      {
        id: 8,
        from: "covi",
        to: "palani",
        kg: 7,
      },
    ],
  };
  render() {
    return (
      <Context.Provider value={this.state}>
        {" "}
        {this.props.children}{" "}
      </Context.Provider>
    );
  }
}

export const Consumer = Context.Consumer;
